### ISSUE TITLE
Password can't be changed

### ISSUE THREAD

**Issue by MatCAlves** [NemProject/NEMAndroidApp#233] opened 2016-06-30 23:13 UTC
Hello my New Economy Movement mates. This is my first issue in Github and I ask to you to help me if I am doing something wrong. So, lets get started. I am testing the app around before start to "play" with some TestXEM, then I have none wallet set yet. 

It is not possible to change the app login password, when I try to do that all seems to be done, but if I need to re-login to the app for some reason, the new password doesn't work, just the old one does. Assuming that is the first run configuration and these device configs:

Samsung Galaxy On7
Android 5.1.1
Kernel: 3.10.49
CPU: Qualcomm Snapdragon 400/410 1.2Ghs x4
NEM Mobile App version: 1.0.49.b3200
My NEM NCC wallet: NDTPKDYJSLT7RXQKJVE5CIJJDO5CY4CNX73LA2N5

Setting a new password:
![screenshot_2016-06-30-20-04-34](https://cloud.githubusercontent.com/assets/20224023/16507236/c112cd8e-3efe-11e6-8676-e17814ed941a.png)

New app password correctly typed:
![screenshot_2016-06-30-20-05-31](https://cloud.githubusercontent.com/assets/20224023/16507241/cad517aa-3efe-11e6-9cfb-133643c89b08.png)

**Comment by fyahfox** [comment] 2016-07-06 21:06
I cannot reproduce this bug.
Did you type the password correctly 100% sure?

Since this is a pretty important problem, @am4n0w4r could you please comment?

**Comment by zachamo** [comment] 2016-07-06 21:29
I also cannot reproduce this -- password change works fine for me.

**Comment by MatCAlves** [comment] 2016-07-07 10:35
That bug only happened in the past, when I didn't have imported a testnet adress yet. Just after I did that, I was able to change the password. And I didn't do any reinstalling process until now.

**Comment by fyahfox** [comment] 2016-07-12 20:02
So when you delete all your accounts, it happens again?

**Comment by MatCAlves** [comment] 2016-07-13 22:34
Correct. I am now without any account, I tried to set a new password again and it didn't work. I reinstalled the app and cleared its data and cache, no success. It looks like a light bug since the app needs that the user have no accounts configured, thus it happens. Anyway, that is still dangerous.

**Comment by fyahfox** [comment] 2016-07-14 18:05
Yes, that is not an acceptable bug, I agree. Thanks!

**Comment by am4n0w4r** [comment] 2016-07-15 10:14
Fixed in 1.0.51

**Closed** 2016-07-26 18:38 UTC
Labels: bug, mustfix, resolved

**Comment by jabo38** [comment] 2016-08-02 17:40
Bounty paid. Tx hash: 01434c50a60b7d59e796c5e0c2d461a02ad7054c68fe70f5e40f0aca564bc00b
