### ISSUE TITLE
Unconfirmed Transaction not showing up

### ISSUE THREAD

**Issue by jabo38** [NemProject/NEMAndroidApp#190] opened 2016-04-01 18:57 UTC
When I make a transaction, I would think it would be at the bottom of the transaction conversations written in grey, but it isn't.  If I go back to Dashboard and then back into the account a 2nd time, then I can see it.

**Comment by jabo38** [comment] 2016-04-03 04:03
Additionally there is no sign of any unconfirmed transactions in the dashboard.

**Comment by am4n0w4r** [comment] 2016-04-04 13:20
Checked this issue. Transactions are updated right after closing the "Transaction sent" dialog and appearing in the bottom as they should. Maybe there is some delay on server between accepting transaction and returning it as unconfirmed, and update is performed too fast to show it. In that case, it will be shown only at next update after 30 sec. Added 0.5sec delay before refreshing data, maybe this will help, in 0.1.47

**Comment by am4n0w4r** [comment] 2016-04-08 12:55
Worked with unconfirmed transactions last few days. They always appeared as they should, just sometimes not right away after sending, 1.0.47

**Comment by fyahfox** [comment] 2016-06-08 11:24
I still often don't see unconfirmed transactions right after sending (1.0.49), please increase delay to 1 second or insert another reload after 5 seconds?

**Comment by am4n0w4r** [comment] 2016-07-14 08:45
This is not an issue with long server response, the problem is that server returns transactions without last transaction attached (it may still be processed when we're doing a reload). Ideally this should work using server push notifications, i.e. when new transaction arrives, server sends a message to clients so they can update UI. What we can do now is increase a delay before first update and try to set another update with hope that this new transaction gets processed and returned before it.

**Comment by am4n0w4r** [comment] 2016-07-14 13:52
Added two more frequent updates after sending, in 1.0.50;

**Comment by fyahfox** [comment] 2016-07-14 18:07
works for me! thx

**Closed by fyahfox** 2016-07-14 18:07 UTC
Labels: bug, mustfix, resolved
