### ISSUE TITLE
QR scanner not working.

### ISSUE THREAD

**Issue by Pilabio** [NemProject/NEMAndroidApp#223] opened 2016-06-21 17:19 UTC
When i try to open the scanner from the app, it shows a message saying: "Barcode scanner dependecies not available", and it don't work at all. It happens when I try to open from inside an account, as when I'm creating one as shown bellow: 

This is from inside an account (pilabius):
![13487884_1058113977569700_2144901893_n](https://cloud.githubusercontent.com/assets/14796384/16239190/227c2706-37ba-11e6-8724-318ecf7d0793.png)

This is when we click to add a new one:
![13511621_1058122344235530_251430680_n](https://cloud.githubusercontent.com/assets/14796384/16239195/25af5e52-37ba-11e6-88fc-693fbb1335db.png)

My phone is an Android and the especifications are these:

Model: Samsung Galaxy J2 2015
Android: 5.1.1
Model number: SM-J200BT 
Kernel: 3.10.9-8281404
            dpi@SWDD6509 #1 
            Fri Jun 3 03:41:22 KST 2016
Build: LMY47X.J200BTUBU1APF3
Chipset: SAMSUNG Exynos 3 Quad 3475 Cortex-A7

My NEM adress:
NA4MWQ-PGFFCD-RFP3QD-JTHCJZ-5WJY6A-RDECK2-WJ3O

**Comment by zachamo** [comment] 2016-06-26 02:05
QR scanner worked fine on my phone

Moto X 2nd Gen
Android 6.0 
NEM demo release v1.0.49.b3200

**Comment by victoru** [comment] 2016-06-27 05:32
I'm also experiencing this issue. 
I'm using the barcode scanner from https://github.com/zxing/zxing.

Sony Xperia Z5 Compact
Android 6.0.1
 NEM v1.0.49.b3200 BETA

**Comment by fyahfox** [comment] 2016-07-06 21:16
@am4n0w4r Please look into it. I heard this from several people now.

**Comment by am4n0w4r** [comment] 2016-07-14 14:46
Duplicate of #209

**Comment by fyahfox** [comment] 2016-07-14 18:31
oops sorry^^

**Closed by fyahfox** 2016-07-14 18:31 UTC
Labels: bug, duplicate, mustfix
